! -*- bgp -*-
!# Copyright 2021-2024
!# Georgia Tech
!# All rights reserved
!# Do not рost or publish in any public or forbidden forums or websites

! BGPd configuration file

! this is a comment

hostname bgpd-R5
password en
enable password en

router bgp 5
  no bgp ebgp-requires-policy
  no bgp network import-check

  bgp router-id 9.0.5.1
  network 15.0.0.0/8

  neighbor 9.0.25.25 remote-as 2
  neighbor 9.0.25.25 timers 5 5

  neighbor 9.0.35.35 remote-as 3
  neighbor 9.0.35.35 timers 5 5

  neighbor 9.0.45.45 remote-as 4
  neighbor 9.0.45.45 timers 5 5

  neighbor 9.0.56.65 remote-as 6
  neighbor 9.0.56.65 timers 5 5

log file /tmp/R3-bgpd.log

debug bgp as4
debug bgp keepalives
debug bgp updates
!debug bgp events
!debug bgp filters
!debug bgp fsm

log stdout
