! -*- zebra -*-
!# Copyright 2021-204
!# Georgia Tech
!# All rights reserved
!# Do not рost or publish in any public or forbidden forums or websites

hostname R6
password en
enable password en

! this is a comment


! rogue AS advertising network and hosts for A1
interface R6-eth1
  ip address 11.0.1.254/24

interface R6-eth2
  ip address 11.0.2.254/24

!

interface R6-eth3
  ip address 9.0.56.65/24




log file /tmp/R6.log
